version: '3.8'

services:
  front_end_web_consumer:
    container_name: "front_end_web_consumer"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app

networks:
  app:
    external: true